
# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID

# cutter mechanism:
mx64:
  ID: 2
  Return_Delay_Time: 0
  # Goal_Position: 2000   #startup
  Goal_Position: 1000   #all metal gear test



# gripper mechanism:
mx28:
  ID: 3
  Return_Delay_Time: 0
  # Goal_Position: 2700 #startup
  Goal_Position: 2300 #all metal gear test

